apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-service-account
  namespace: materclaims
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/AppServiceAccountRole
