apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dapr-component-reader
  namespace: dapr-demo
rules:
- apiGroups: ["dapr.io"]
  resources: ["components", "configurations"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dapr-service-account-component-reader
  namespace: dapr-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dapr-component-reader
subjects:
- kind: ServiceAccount
  name: dapr-service-account
  namespace: dapr-demo
